services:
  - type: web
    name: myshop
    env: java
    region: frankfurt
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      # Временная БД для теста
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:testdb